language: php

cache:
  directories:
    - $HOME/.composer/cache
    - $HOME/.npm

matrix:
 allow_failures:
 fast_finish: true
 include:
 - php: 7.2
   env: DB=mysqli
   services: mysql
 - php: 7.2
   env: DB=pgsql
   services: postgresql
   addons:
      postgresql: 9.5
 - php: 7.4
   env: DB=mysqli
   services: mysql
 - php: 7.4
   env: DB=pgsql
   services: postgresql
   addons:
      postgresql: 9.5
env:
 global:
  - MOODLE_BRANCH=MOODLE_310_STABLE
  - IGNORE_PATHS=javascript/syntaxhighlighter_3_0_83/,javascript/syntaxhighlighter_4_0_1/,templates/mod_assign
  - IGNORE_NAMES=*.txt,mustache_filesystem_loader.php,fallback.css,fontawesome.css

before_install:
# This disables XDebug which should speed up the build.  One reason to remove this
# line is if you are trying to generate code coverage with PHPUnit.
  - phpenv config-rm xdebug.ini
# Currently we are inside of the clone of your repository.  We move up two
# directories to build the project.
  - cd ../..
# Update Composer.
  - composer selfupdate
# Install this project into a directory called "ci".
  - composer create-project -n --no-dev --prefer-dist moodlehq/moodle-plugin-ci ci ^3
# Update the $PATH so scripts from this project can be called easily.
  - export PATH="$(cd ci/bin; pwd):$(cd ci/vendor/bin; pwd):$PATH"

install:
  - moodle-plugin-ci install
# npm
  - npm install eslint@latest
  - npm install eslint-plugin-babel@latest
  - npm install eslint-plugin-promise@latest

script:
  - moodle-plugin-ci phplint
  - moodle-plugin-ci phpcpd
  - moodle-plugin-ci phpmd
  - moodle-plugin-ci codechecker
  - moodle-plugin-ci validate
  - moodle-plugin-ci mustache
  - moodle-plugin-ci phpdoc
  - moodle-plugin-ci phpunit
